Models/Comments/MainComment.cs
namespace EcommerceApp.Models.Comments
{
    public class MainComment : Comment
    {
        public List<SubComment> SubComments { get; set; }
    }
}

Models/ViewModels/DashboardViewModel.cs
namespace EcommerceApp.Models.ViewModels
{
    public class DashboardViewModel
    {
        public List<Product?> Products { get; set; }

        public List<TodoList?> TodoLists { get; set; }

        public List<MyMessage> MyMessages { get; set; }

        public List<Post> Posts { get; set; }
    }
}

Areas/Admin/Controllers/DashboardController.cs
using EcommerceApp.Data;
using EcommerceApp.Data.Repository.IRepository;
using EcommerceApp.Models;
using EcommerceApp.Models.ViewModels;
using EcommerceApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EcommerceApp.Areas.Admin.Controllers
{
    [Area("Admin")]
     [Authorize(Roles = SD.Role_Admin)]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
   
        public DashboardController(ApplicationDbContext context,
            IUnitOfWork unitOfWork)
        {
            _context = context;
           
        }
        public async Task<ActionResult> Index()
        {
            var model = new DashboardViewModel();

            model.Products = _context.Products.ToList(); ; 
            model.TodoLists = _context.TodoLists.ToList();
            model.MyMessages = _context.MyMessages.ToList();
            model.Posts = _context.Posts.ToList();

            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> PlotlyBarChart()
        {
            var products = await _context.Products.ToListAsync();

            var plotData = new List<Object>
            {
                new
                {
                    x = products.Select(p=>p.Name).ToArray(),
                    y = products.Select(p=>p.Price).ToArray(),
                    type = "bar",
                    name = "Price"
                },
                new
                {
                    x = products.Select(p => p.Name).ToArray(),
                    y = products.Select(p => p.ListPrice).ToArray(),
                    type = "bar",
                    name = "List Price"
                }
            };

            return Json(plotData);
        }
    }
}

ViewComponents/ShoppingCartViewComponent.cs
using EcommerceApp.Data.Repository.IRepository;
using EcommerceApp.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EcommerceApp.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

Views/Shared/_AdminSideNavbar.cshtml
﻿<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Panel">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Admin Panel<sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseMessages"
           aria-expanded="true" aria-controls="collapseMessages">
            <i class="fas fa-fw fa-cog"></i>
            <span>MyMessages</span>
        </a>
        <div id="collapseMessages" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Daily Messages:</h6>
                <a class="collapse-item" href="/Admin/mymessages">Messages Lists</a>
                <a class="collapse-item" href="cards.html">Reminder</a>
            </div>
        </div>
    </li>



    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <!-- Posts Area-->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePosts"
           aria-expanded="true" aria-controls="collapsePosts">
            <i class="fas fa-fw fa-folder"></i>
            <span>Posts</span>
        </a>
        <div id="collapsePosts" class="collapse" aria-labelledby="headingPosts" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Daily Posts :</h6>
                <a class="collapse-item" href="/Admin/Posts">Posts List</a>
                <a class="collapse-item" href="/Admin/Posts/Edit">Input Posts</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <!-- Parts Area-->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseParts"
           aria-expanded="true" aria-controls="collapseParts">
            <i class="fas fa-fw fa-folder"></i>
            <span>Parts</span>
        </a>
        <div id="collapseParts" class="collapse" aria-labelledby="headingParts" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Parts Inventory:</h6>
                <a class="collapse-item" href="/Admin/Parts">Parts List</a>
                <a class="collapse-item" href="/Admin/Parts/Create">Input Parts</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProducts"
           aria-expanded="true" aria-controls="collapseProducts">
            <i class="fas fa-fw fa-folder"></i>
            <span>Products</span>
        </a>
        <div id="collapseProducts" class="collapse" aria-labelledby="headingProducts" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Products Inventory:</h6>
                <a class="collapse-item" href="/Admin/Product">Products List</a>
                <a class="collapse-item" href="/Admin/Product/Upsert">Input Products</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCategory"
           aria-expanded="true" aria-controls="collapseCategory">
            <i class="fas fa-fw fa-folder"></i>
            <span>Category</span>
        </a>
        <div id="collapseCategory" class="collapse" aria-labelledby="headingCategory" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category Inventory:</h6>
                <a class="collapse-item" href="/Admin/Category">Category List</a>
                <a class="collapse-item" href="/Admin/Category/Create">Input Category</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseTodo"
           aria-expanded="true" aria-controls="collapseTodo">
            <i class="fas fa-fw fa-folder"></i>
            <span>MyTodo-List</span>
        </a>
        <div id="collapseTodo" class="collapse" aria-labelledby="headingTodo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">MyTodo-List:</h6>
                <a class="collapse-item" href="/Admin/TodoList">Todo List</a>
                <a class="collapse-item" href="/Admin/TodoList/Create">Input Todo</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span>
        </a>
    </li>
    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span>
        </a>
    </li>
    <!-- Nav Item - Calculator -->
    <partial name="_CalculatorPanel" />
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

Views/Shared/_AdminTopBar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
   
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        
        
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Hello @UserManager.GetUserName(User)!</span>
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Account Settings
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

Views/Shared/_CalculatorPanel.cshtml
<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCalculator"
       aria-expanded="true" aria-controls="collapseCalculator">
        <i class="fas fa-fw fa-calculator"></i>
        <span>Calculator</span>
    </a>
    <div id="collapseCalculator" class="collapse" aria-labelledby="headingCalculator" data-parent="#accordionSidebar">
        <div class="bg-gradient-info py-2 collapse-inner rounded">
            <div class="calculator-grid">
                <div class="output">
                    <div data-previous-operand class="previous-operand"></div>
                    <div data-current-operand class="current-operand"></div>
                </div>
                <button data-all-clear class="span-two">AC</button>
                <button data-delete>DEL</button>
                <button data-operation>÷</button>
                <button data-number>1</button>
                <button data-number>2</button>
                <button data-number>3</button>
                <button data-operation>*</button>
                <button data-number>4</button>
                <button data-number>5</button>
                <button data-number>6</button>
                <button data-operation>+</button>
                <button data-number>7</button>
                <button data-number>8</button>
                <button data-number>9</button>
                <button data-operation>-</button>
                <button data-number>.</button>
                <button data-number>0</button>
                <button data-equals class="span-two">=</button>
            </div>
        </div>
    </div>
</li>


<script src="~/js/calculator.js"></script>

Views/Shared/_DashBoard.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<html xmlns="http://www.w3.org/1999/xhtml">
    <head><title></title></head>
    <body>This is DashBoard</body>
</html>

Views/Shared/_Footer.cshtml
@using EcommerceApp.Utility

@if (!User.IsInRole(SD.Role_Admin))
{
﻿<!-- Footer -->
    <footer class="text-center footer bg-dark bg-primary">
        <div class="footer-above">
            <div class="container-fluid">
                <div class="row">
                    <div class="footer-col col-lg-4 col-md-6 col-sm-6">
                        <h4 class="text-capitalize text-white"><span style="color:red;">Online/</span>Parts</h4>
                        <i class="fa fa-wrench fa-3x" style="color:white"></i>
                        <br>
                        <br><i class="fa fa-phone" style="color:white"></i><span style="color:white;"> 863-216-8903</span>
                        <br><i class="fa fa-home" style="color:white"></i><span style="color:white;"> Mon - Sat 10am to 5pm</span>
                        <br><i class="fa fa-envelope" style="color:white"></i><a href="mailto:electronicsmf@aol.com"><span style="color:white;"> Electronicsmf@aol.com</span></a>
                        <br><i class="fa fa-envelope" style="color:white"></i><a href="/UI/Messages/New"><span style="color:white;"> Contact Page</span></a>
                    </div>
                    <div class="footer-col col-lg-4 col-md-6 col-sm-6">
                        <h4 class="text-capitalize text-white">Around the Web</h4>
                        <ul class="social-network social-circle">
                            <li>
                                <a href="" class="icoFacebook" title="Facebook"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="" class="icoGoogle" title="Google"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="" class="icoYelp" title="yelp"><i class="fa fa-fw fa-yelp"></i></a>
                            </li>
                            <li>
                                <a href="#" class="icoDribbble" title="Dribbble"><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-lg-4 col-md-6 col-sm-6">
                        <h4 class="text-capitalize">Payments</h4>
                        <img src="~/images/payment.webp" class="img-fluid" alt="credit_card_payment">
                    </div>
                </div><!--row-->
            </div><!--container-->
        </div><!--footer above-->
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p>&copy; @DateTime.Now.Year - Online Store Parts.All Rights Reserved.</p>
                        <br /><span>Website design by <a href="http://Martindevs.online/"><strong>MartinDevs.online</strong></a></span>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <a class="back-to-top hidden-xs-down show" id="back-to-top"><i class="fa fa-3x fa-angle-up"></i></a>
}

Views/Shared/_Header.cshtml
@using EcommerceApp.Utility

 @if (!User.IsInRole(SD.Role_Admin))
{
    <header>
        <div class="top-header bg-secondary pt-2 pb-1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6 text-center text-md-start">
                        <span class="text-white">Connect With Us:</span>
                        <ul class="list-inline d-inline-block">
                            <li class="list-inline-item"><a class="text-white d-inline-block p-2" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li class="list-inline-item"><a class="text-white d-inline-block p-2" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a class="text-white d-inline-block p-2" href="#"><i class="fa fa-rss"></i></a></li>
                            <li class="list-inline-item"><a class="text-white d-inline-block p-2" href="#"><i class="fa fa-google"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-md-6 text-md-right text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item mx-0 border-secondary"><a class="text-white d-inline-block px-lg-3 px-2" href="mailto:electronicsmf@aol.com">Email Me to: Electronicsmf@aol.com</a></li>
                            <li class="list-inline-item mx-0"><a class="text-white d-inline-block px-lg-3 px-2" href="callto:86332168903">Call Us Now: <span class="text-primary">863-216-8903</span></a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <partial name="_Navbar" />
    </header>
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using EcommerceApp.Utility
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommerceApp</title>
    <link href="~/css/sb-admin-2.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
    <link href="~/styles/Layout/_Footer.css" rel="stylesheet" />
    <link href="~/styles/Layout/_Post.css" rel="stylesheet" />
    <link href="~/styles/Layout/_Home.css" rel="stylesheet" />
    <link href="~/css/calculator.css" rel="stylesheet" />
    <link href="~/css/post.css" rel="stylesheet" />
</head>
<body>
    <!-- preloader start -->
    <div class="preloader">
        <div class="spin"></div>
    </div>
    <partial name="_Header" />
    <div class="container-box" class="pb-3">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <partial name="_Footer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    <script src="~/js/preloader.js"></script>
    <script src="~/js/scrolltop.js"></script>
    <script src="~/js/togglemenu.js"></script>
    <script src="~/js/sb-admin-2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Http
@using EcommerceApp.Utility
@inject IHttpContextAccessor HttpContextAccessor


    <nav class="navbar navbar-expand-md navbar-toggleable navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo/onestop-white.png" style="width:100px;padding:5px" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Posts" asp-action="Index">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Manage Order</a>
                    </li>
                    @if (User.IsInRole(SD.Role_Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin"
                               asp-for="Admin" asp-controller="Panel" asp-action="Index">Panel</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class=nav-link asp-area="UI" asp-controller="Cart" asp-action="Index">
                            @await Component.InvokeAsync("ShoppingCart")
                        </a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>